### ISSUE TITLE
Problema ao instalar em Raspberry PI OS Debian Bullseye 22-09-2022

### ISSUE THREAD

**Issue by leosted** [Manuel83/craftbeerpi4#105]
Raspaberry PI 3B

Hardware        : BCM2835
Revision        : a52082
Serial          : 000000007ed3f875
Model           : Raspberry Pi 3 Model B Rev 1.2

SO - Raspberry PI OS  Debian Bullseye 22-09-2022
Ao tentar instalar conforme o site https://openbrewing.gitbook.io/craftbeerpi4_support/readme/server-installation

Após rodar o comando -- cbpi setup -- aparecee o seguinte erro:

Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 5, in <module>
    from cbpi.cli import main
  File "/usr/local/lib/python3.9/dist-packages/cbpi/cli.py", line 6, in <module>
    from cbpi.craftbeerpi import CraftBeerPi
  File "/usr/local/lib/python3.9/dist-packages/cbpi/craftbeerpi.py", line 38, in <module>
    from cbpi.controller.satellite_controller import SatelliteController
  File "/usr/local/lib/python3.9/dist-packages/cbpi/controller/satellite_controller.py", line 5, in <module>
    from asyncio_mqtt import Client, MqttError, Will, client
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/__init__.py", line 2, in <module>
    from .client import Client, ProtocolVersion, TLSParameters, Will
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 35, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)

**Comment by leosted** [comment]
resolvido, mas podem colocar no script ou no manual

pip install --no-cache fastapi

**Comment by StealthChicken** [comment]
Try

sudo pip3 install -U typing_extensions
