### ISSUE TITLE
Issue with clean installation of cbpi 4.0.0.21 -> file config.json is not available

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#26]
No matter if cbpi is installed as pacakge from pypi or from the git repo. First error message is when I want to setup:

```
Setting up CraftBeerPi
Folder created
Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 229, in setup
    create_config_file()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 51, in create_config_file
    shutil.copy(srcfile, destfile)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/cbpi/config/config.json'
```

In this folder is a config.yaml file. Not sure if this should be the json file or not.

**Comment by avollkopf** [comment]
My bad. accidently added sudo during installation from the venv... Will close this one, but still have issues in a venv. I need to dig into tha tonight

**Comment by avollkopf** [comment]
Still get the same error in the venv. Samm messages as above, just different folder.

Installed via pip3 install  https://github.com/Manuel83/craftbeerpi4/archive/master.zip

`FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/venv/lib/python3.7/site-packages/cbpi/config/config.json'
`

**Comment by BrauereiAlt** [comment]
Similar here.  There doesn’t seem to be a config.json file in the package, at least none was installed, yet it is referenced in lines 48 & 49 of cbpi/cli.py.

**Comment by avollkopf** [comment]
An online conversion of the config.yaml to json format does not really help. This error is gone, but other errors while reading the config pop up. I assume the new config has also some other parameters included.

**Comment by Manuel83** [comment]
Please make sure to run cbpi setup

There are to config files

1. config.yaml -> Static file which can not be changed at run time
2. config.json -> Config file which can be change at runtime via UI

Maybe I need to rename it to 

static_config.yaml
runtime_config.json

**Comment by vojtech** [comment]
I have the same issue.
```
pi@raspberrypi:~ $ cbpi setup
Setting up CraftBeerPi
Folder created
Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 229, in setup
    create_config_file()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 51, in create_config_file
    shutil.copy(srcfile, destfile)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/cbpi/config/config.json'
pi@raspberrypi:~ $ 


```
