### ISSUE TITLE
Can't start after upgrading to .27

### ISSUE THREAD

**Issue by Biffe46** [Manuel83/craftbeerpi4#39]
After upgrading to .27 I can't log onto the server. 

added the full log from: cbpi start

pi@raspberrypi:~ $ cbpi start
START
2021-02-28 19:42:27,930 - INFO - cbpi.craftbeerpi - Init CraftBeerPI
2021-02-28 19:42:28,093 - INFO - cbpi.eventbus - Topic #
2021-02-28 19:42:28,435 - INFO - cbpi.craftbeerpi -
  _____            __ _   ____                 _____ _
 / ____|          / _| | |  _ \               |  __ (_)
| |     _ __ __ _| |_| |_| |_) | ___  ___ _ __| |__) |
| |    | '__/ _` |  _| __|  _ < / _ \/ _ \ '__|  ___/ |
| |____| | | (_| | | | |_| |_) |  __/  __/ |  | |   | |
 \_____|_|  \__,_|_|  \__|____/ \___|\___|_|  |_|   |_|

 _  _    ___   ___   ___ ______
| || |  / _ \ / _ \ |__ \____  |
| || |_| | | | | | |   ) |  / /
|__   _| | | | | | |  / /  / /
   | |_| |_| | |_| | / /_ / /
   |_(_)\___(_)___(_)____/_/

2021-02-28 19:42:28,435 - INFO - cbpi.craftbeerpi - www.CraftBeerPi.com
2021-02-28 19:42:28,436 - INFO - cbpi.craftbeerpi - (c) 2021 Manuel Fritsch
2021-02-28 19:42:28,443 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin gpioactor
2021-02-28 19:42:28,486 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin hysteresis
2021-02-28 19:42:28,492 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin mashstep
2021-02-28 19:42:28,499 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin dummysensor
2021-02-28 19:42:28,504 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin dummyactor
2021-02-28 19:42:28,509 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin mqtt
2021-02-28 19:42:28,512 - WARNING - cbpi.controller.plugin_controller - Plugin m                                                                                       qtt is not supporting version 4
2021-02-28 19:42:28,513 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin httpsensor
2021-02-28 19:42:28,520 - INFO - cbpi.controller.plugin_controller - Trying to l                                                                                       oad plugin onewire
2021-02-28 19:42:28,557 - INFO - cbpi.controller.plugin_controller - Try to load                                                                                        plugin:  cbpi4ui
2021-02-28 19:42:28,564 - INFO - cbpi.controller.plugin_controller - Plugin cbpi                                                                                       4ui loaded successfully
2021-02-28 19:42:28,564 - INFO - cbpi.controller.plugin_controller - Try to load                                                                                        plugin:  cbpi4-pt100x
2021-02-28 19:42:28,569 - INFO - cbpi.controller.plugin_controller - Plugin cbpi                                                                                       4-pt100x loaded successfully
2021-02-28 19:42:28,569 - INFO - root - SensorController Load
2021-02-28 19:42:28,571 - INFO - root - SensorController Starting
2021-02-28 19:42:28,571 - INFO - root - SensorController Start Id QZ28TDSp5ey2wu                                                                                       emP9nAhB
2021-02-28 19:42:28,571 - INFO - root - SensorController started QZ28TDSp5ey2wue                                                                                       mP9nAhB
2021-02-28 19:42:28,572 - INFO - root - SensorController Starting
2021-02-28 19:42:28,572 - INFO - root - SensorController Start Id TowgMULqaBj9iL                                                                                       PmQ5jo7V
2021-02-28 19:42:28,573 - INFO - root - SensorController started TowgMULqaBj9iLP                                                                                       mQ5jo7V
2021-02-28 19:42:28,573 - INFO - root - SensorController Starting
2021-02-28 19:42:28,573 - INFO - root - SensorController Start Id boJuATtoVvGbWo                                                                                       fus6TusK
2021-02-28 19:42:28,574 - INFO - root - SensorController started boJuATtoVvGbWof                                                                                       us6TusK
2021-02-28 19:42:28,574 - INFO - root - SensorController Starting
2021-02-28 19:42:28,574 - INFO - root - SensorController Start Id SGsxcnpm4QhvaQ                                                                                       T3RSsKQa
2021-02-28 19:42:28,574 - INFO - root - SensorController started SGsxcnpm4QhvaQT                                                                                       3RSsKQa
2021-02-28 19:42:28,575 - INFO - root - SensorController Starting
2021-02-28 19:42:28,575 - INFO - root - SensorController Start Id MNVtTna589QbpW                                                                                       pLFWiPu3
2021-02-28 19:42:28,576 - INFO - root - SensorController started MNVtTna589QbpWp                                                                                       LFWiPu3
2021-02-28 19:42:28,576 - INFO - root - SensorController Starting
2021-02-28 19:42:28,577 - INFO - root - SensorController Start Id mfKjtPgfWqm2Kx                                                                                       RRJAozJX
2021-02-28 19:42:28,577 - INFO - root - SensorController started mfKjtPgfWqm2KxR                                                                                       RJAozJX
2021-02-28 19:42:28,578 - INFO - root - INIT STEP Controller
2021-02-28 19:42:29,093 - ERROR - asyncio - unhandled exception during asyncio.r                                                                                       un() shutdown
task: <Task finished coro=<_run_app() done, defined at /usr/local/lib/python3.7/                                                                                       dist-packages/aiohttp/web.py:287> exception=KeyError('steps')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 508, in run                                                                                       _app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_compl                                                                                       ete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 307, in _ru                                                                                       n_app
    app = await app  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 260, i                                                                                       n init_serivces
    await self.step.init()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.p                                                                                       y", line 30, in init
    self.load(startActive=True)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.p                                                                                       y", line 64, in load
    self.profile = data["steps"]
KeyError: 'steps'
Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __ca                                                                                       ll__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in inv                                                                                       oke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in inv                                                                                       oke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invo                                                                                       ke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 251, in start
    cbpi.start()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 272, i                                                                                       n start
    web.run_app(self.init_serivces(), port=self.static_config.get("port", 2202))
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 508, in run                                                                                       _app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_compl                                                                                       ete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 307, in _ru                                                                                       n_app
    app = await app  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 260, i                                                                                       n init_serivces
    await self.step.init()
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.p                                                                                       y", line 30, in init
    self.load(startActive=True)
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/step_controller.p                                                                                       y", line 64, in load
    self.profile = data["steps"]
KeyError: 'steps'
pi@raspberrypi:~ $

**Comment by BrauereiAlt** [comment]
Did you delete your old config directory and run a fresh cbpi setup and make sure cbpi4u1 is upgraded to version 0.0.12 before running cbpi start?  You need to in order for an upgrade to cbpi build 27 to run correctly.

**Comment by Biffe46** [comment]
Installed v0.0.12 didnt work, so I reinstalled cbpi and as you can see that 0.0.12 is installed. Requirement already satisfied: cbpi4ui in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.27) (0.0.12)

Still get the same error. Any ideas?

**Comment by BrauereiAlt** [comment]
But did you delete your working config directory before you ran cbpi setup? If you don’t delete config, setup will leave your original JSON files which will likely conflict with changes made in build 27.  At least that was my experience.

**Comment by Manuel83** [comment]
Please make sure to delete the config folder.
The mash profile config changed.

This should solve your issue.

**Comment by Biffe46** [comment]
Yeah sorry for the lack of reply. I did that, and it's working fine now. thanks for reply both of you.
