### ISSUE TITLE
Trouble installing CBPI4 on RaspberryPi Zero W - error

### ISSUE THREAD

**Issue by rkhanso** [Manuel83/craftbeerpi4#49]
Following the directions at https://craftbeerpi.gitbook.io/craftbeerpi4/   I'm running into some trouble.

After sudo pip install cbpi    
I get:
pi@raspberrypi:~ $ sudo pip install cbpi
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cbpi
  Using cached https://files.pythonhosted.org/packages/dd/e8/5a43b03a66d797ccd7de14d6942ffd1bcf0647b6b88ae358dd8b02ea1bfa/cbpi-4.0.0.28.tar.gz
Collecting aiohttp-auth==0.1.1 (from cbpi)
  Using cached https://files.pythonhosted.org/packages/74/1d/261bb7e86b660cb5bdb1f4c28393d8078c189eddc1c87cd16389dfca8500/aiohttp_auth-0.1.1.tar.gz
Collecting aiohttp-route-decorator==0.1.4 (from cbpi)
  Using cached https://files.pythonhosted.org/packages/4f/b6/3af0444d36812b68367c3bb8ff65d0ccf5ba855ce28cda5ce10ff465021a/aiohttp_route_decorator-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lPYWOK/aiohttp-route-decorator/setup.py", line 13, in <module>
        long_description=open('README.rst', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lPYWOK/aiohttp-route-decorator/**

After sudo pip install https://github.com/Manuel83/craftbeerpi4/archive/master.zip    
I get:
pi@raspberrypi:~ $ sudo pip install https://github.com/Manuel83/craftbeerpi4/archive/master.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/Manuel83/craftbeerpi4/archive/master.zip
  Downloading https://github.com/Manuel83/craftbeerpi4/archive/master.zip
     - 50.6MB 1.7MB/**sKilled**
pi@raspberrypi:

After sudo pip install https://github.com/Manuel83/craftbeerpi4.git   
I get:
pi@raspberrypi:~ $ sudo pip install https://github.com/Manuel83/craftbeerpi4.git
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/Manuel83/craftbeerpi4.git
  Downloading https://github.com/Manuel83/craftbeerpi4.git
     | 194kB 1.2MB/s
  **Cannot unpack file /tmp/pip-unpack-s9im6y/craftbeerpi4.git (downloaded from /tmp/pip-req-build-q6nOW4, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-q6nOW4**

**Comment by Prash3r** [comment]
duplicate of #36 

you are trying to use python2.x while this is a python3.x project.

> wild guess: you are probably using python 2.x and should use python 3.x (im running Python 3.9.2).
> 
> run `python --version` to find out which version is installed as the default on your machine.
> 
> This is a python 3 project. ty running the setup with the `python3` command

_Originally posted by @Prash3r in https://github.com/Manuel83/craftbeerpi4/issues/36#issuecomment-786945382_

**Comment by maynardpa** [comment]
I was about to report the same issue but want to report that I am getting further by using this simple command-line altered command on my raspberry pi 3 with the latest raspbian release (March 4th 2021).

sudo pip3 install cbpi

Cheers!

**Comment by wilbeblay** [comment]
I get the exact same error on mac and my raspberry pi 3b, I have updated to the latest python3 and did the setup tools still no luck. Should I uninstall python and pty again or is there another trick?

**Comment by avollkopf** [comment]
> 
> 
> I get the exact same error on mac and my raspberry pi 3b, I have updated to the latest python3 and did the setup tools still no luck. Should I uninstall python and pty again or is there another trick?

What is the output of python --version and pip --version ? This needs to be linked to python3. if thiese commands show 2.X versions,it won't be working. In this case you can install the update alternatives and set python 3 as default.

https://stackoverflow.com/questions/43062608/how-to-update-alternatives-to-python-3-without-breaking-apt

**Comment by wilbeblay** [comment]
> > I get the exact same error on mac and my raspberry pi 3b, I have updated to the latest python3 and did the setup tools still no luck. Should I uninstall python and pty again or is there another trick?
> 
> What is the output of python --version and pip --version ? This needs to be linked to python3. if thiese commands show 2.X versions,it won't be working. In this case you can install the update alternatives and set python 3 as default.
> 
> https://stackoverflow.com/questions/43062608/how-to-update-alternatives-to-python-3-without-breaking-apt


Thank you,

I had to add python3 to the bashrc file to make it default as in the example:
https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux 

Once python3 was set as the default I could install cbpi using: sudo pip3 install cbpi
