### ISSUE TITLE
Can't create custom plugin

### ISSUE THREAD

**Issue by BetterRobotics** [Manuel83/craftbeerpi4#77]
Tried to create a custom plugin but get this error when running `cbpi create BLE_Sensor`

error is:

Traceback (most recent call last):
  File "/home/pi/venv/bin/cbpi", line 10, in <module>
    sys.exit(main())
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/venv/lib/python3.7/site-packages/cbpi/cli.py", line 279, in create
    plugin_create(name)
  File "/home/pi/venv/lib/python3.7/site-packages/cbpi/cli.py", line 186, in plugin_create
    templateLoader = jinja2.FileSystemLoader(searchpath=os.path.join(MAIN_DIR, name))
NameError: name 'MAIN_DIR' is not defined

**Comment by avollkopf** [comment]
which version are you using. This used to be an issue, but has been solved in the latest version from github. It may still be a problem with 4.0.0.28 from pypi.org

**Comment by BetterRobotics** [comment]
Thanks, I can confirm that using the the version from GitHub works 👍
