### ISSUE TITLE
Install on Raspberry OS lite is missing dependency for Numpy

### ISSUE THREAD

**Issue by MikonosII** [Manuel83/craftbeerpi4#9]
Got this error:

Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 6, in <module>
    from cbpi.cli import main
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 11, in <module>
    from cbpi.craftbeerpi import CraftBeerPi
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 25, in <module>
    from cbpi.controller.log_file_controller import LogController
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/log_file_controller.py", line 7, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/dist-packages/pandas/__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.20.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Fix was to install the missing dependency: libatlas-base-dev

or to reinstall Numpy using:

pip3 uninstall numpy  # remove previously installed version
apt install python3-numpy

**Comment by MikonosII** [comment]
1. installed the latest raspberry pi os lite from https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-lite.zip
2. sudo apt-get install python3-pip
3. sudo python3 -m pip install cbpi
4. cbpi setup
5. I got the above error
5. sudo apt-get install libatlas-base-dev
6. cbpi setup
7. runs as advertised

`pi@cbpi:~ $ pip3 list
Package                 Version  
----------------------- ---------
aiohttp                 3.7.3    
aiohttp-auth            0.1.1    
aiohttp-route-decorator 0.1.4    
aiohttp-security        0.4.0    
aiohttp-session         2.9.0    
aiohttp-swagger         1.0.15   
aiojobs                 0.3.0    
aiosqlite               0.16.0   
asn1crypto              0.24.0   
async-timeout           3.0.1    
attrs                   20.3.0   
cbpi                    4.0.0.13 
cbpi4-ui                0.0.3    
certifi                 2018.8.24
cffi                    1.14.4   
chardet                 3.0.4    
click                   7.1.2    
cryptography            3.3.1    
entrypoints             0.3      
idna                    2.6      
Jinja2                  2.11.3   
keyring                 17.1.1   
keyrings.alt            3.1.1    
MarkupSafe              1.1.1    
multidict               5.1.0    
numpy                   1.20.0   
pandas                  1.1.5    
pip                     18.1     
pycparser               2.20     
pycrypto                2.6.1    
pyfiglet                0.8.post1
PyGObject               3.30.4   
python-apt              1.8.4.3  
python-dateutil         2.8.1    
pytz                    2021.1   
pyxdg                   0.25     
PyYAML                  5.4.1    
requests                2.25.1   
SecretStorage           2.3.1    
setuptools              40.8.0   
shortuuid               1.0.1    
six                     1.12.0   
ssh-import-id           5.7      
tabulate                0.8.7    
ticket-auth             0.1.4    
typing-extensions       3.7.4.3  
urllib3                 1.24.1   
voluptuous              0.12.1   
wheel                   0.32.3   
yarl                    1.6.3  '

**Comment by mmillebr** [comment]
same error for me when I tried to upgrade from version 4.0.0.12 to 4.0.0.13 using "sudo python3 -m pip install cbpi --force-reinstall". After install dependencies, WebGUI can not load, returning error:
{"error": "Not Found"}

**Comment by Manuel83** [comment]
Are using a virtual environment?
Can you try a virtual environment? See documentation how to setup this 

https://app.gitbook.com/@craftbeerpi/s/craftbeerpi4/

Can you post the complete error message.

which command raised this error?

**Comment by avollkopf** [comment]
Same her when I do it in a virtual environment on my pi. It's running on my ubuntu container w/o issues. I installed the version from GIThub.

Basically the same message as above.

```
(venv) pi@raspberrypi:~/cbpi4 $ sudo cbpi setup
Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 6, in <module>
    from cbpi.cli import main
  File "/usr/local/lib/python3.7/dist-packages/cbpi/cli.py", line 11, in <module>
    from cbpi.craftbeerpi import CraftBeerPi
  File "/usr/local/lib/python3.7/dist-packages/cbpi/craftbeerpi.py", line 25, in <module>
    from cbpi.controller.log_file_controller import LogController
  File "/usr/local/lib/python3.7/dist-packages/cbpi/controller/log_file_controller.py", line 7, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/dist-packages/pandas/__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.20.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

```

**Comment by avollkopf** [comment]
I retried it this morning and it seems to me that this is related to rights. I can set up a venv and run the installation within the venv (w/o sudo).

Everything seems to install, but some packages cannot be build. if you re-run this later with sudo, the missing packages can be build. 

Setup is working but then I get the numpy error. I can uninstall numpy via pip, but can't install python3-numpy from the virtual environment w/o sudo. If I install it with sudo I get the information that it is already installed. But If I try to start cbpi from the venv I get the error message that numpy is missing. 

If I install it w/o venv, it seem to work. I could also add my plugin for the pt100/pt1000. No error messages, but it does not load. Anyway, I will dig into this with a separate SD card as I am currently running a fermentation and I do not want to screw up the existing cbpi3 installation.

**Comment by lalo-uy** [comment]
The missing dependency is corrected by:

`sudo apt-get install libatlas-base-dev`

**Comment by mmillerbr** [comment]
Mine is solved. I had to uninstall and remove all files in the folder I've used to install cbpi.
After that, I did the installation again using "pip3"and it's working now.
Super cool !

**Comment by avollkopf** [comment]
If I install it from github, folders and databse are not created via cbpi setup (4.0.0.14)

However, everything is installing fine via pip3 install cbpi as package (V4.0.0.13). The setup process is installing the folders and the database and I can start cbpi. 

When I now remove cbpi and the cbpi4-ui package, I can install the github version where the setup process is using the existing foldaers and database. Afterwards cbpi 4.0.0.14 can be started.

Not sure if this is related to the latest update were some folder setting where modified.

It is now running on my pi. However, so far I did not manage it to run in a virtual environment on my pi

I did not notice this behavior on earlier versions on my ubuntu containers running on my NAS. Here I could also install cbpi in venv.

**Comment by staticdev** [comment]
I created an initial PR #74 to avoid this kind of problems. It does not completely solves the problem, but is a step towards better dependency management here.
